services:
  app:
    build: ./app
    container_name: app-php
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
      
  phpmyadmin: 
    image: phpmyadmin:latest 
    container_name: pma 
    environment: 
      - PMA_HOST=db 
      - PMA_USER=${MYSQL_USER} 
      - PMA_PASSWORD=${MYSQL_PASSWORD} 
    ports: 
      - "8081:80" 
    depends_on: 
      - db

volumes:
  db_data:
